# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, TYPE_CHECKING

if TYPE_CHECKING:
    from ...hook0_api import Hook0API


class AuthLogin:
    def __init__(self, parent: "Hook0API"):
        self.parent = parent

    def auth_login(
        self,
        email: str,
        password: str,
    ) -> Any:
        """
        Get an access token using a user's credentials.

        Args:
            email: No description provided
            password: No description provided

        Returns:
            Response data
        """
        path = "/api/v1/auth/login"
        params = None
        headers = None
        json_data = {
            "email": email if email is not None else None,
            "password": password if password is not None else None,
        }
        json_data = {k: v for k, v in json_data.items() if v is not None}

        response = self.parent._make_request(
            method="POST",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
