# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, Optional, TYPE_CHECKING

if TYPE_CHECKING:
    from ...hook0_api import Hook0API


class Register:
    def __init__(self, parent: "Hook0API"):
        self.parent = parent

    def register(
        self,
        email: str,
        first_name: str,
        last_name: str,
        password: str,
        turnstile_token: Optional[str] = None,
    ) -> Any:
        """
        If instance has Cloudflare Turnstile enabled (see response of /instance endpoint), the `turnstile_token` field is mandatory.

        Args:
            email: No description provided
            first_name: No description provided
            last_name: No description provided
            password: No description provided
            turnstile_token: No description provided

        Returns:
            Response data
        """
        path = "/api/v1/register/"
        params = None
        headers = None
        json_data = {
            "email": email if email is not None else None,
            "first_name": first_name if first_name is not None else None,
            "last_name": last_name if last_name is not None else None,
            "password": password if password is not None else None,
            "turnstile_token": turnstile_token if turnstile_token is not None else None,
        }
        json_data = {k: v for k, v in json_data.items() if v is not None}

        response = self.parent._make_request(
            method="POST",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
