# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

from typing import TYPE_CHECKING

from .organizations_list.organizations_list import OrganizationsList
from .organizations_create.organizations_create import OrganizationsCreate
from .organizations_get.organizations_get import OrganizationsGet
from .organizations_edit.organizations_edit import OrganizationsEdit
from .organizations_delete.organizations_delete import OrganizationsDelete
from .organizations_edit_role.organizations_edit_role import OrganizationsEditRole
from .organizations_invite.organizations_invite import OrganizationsInvite
from .organizations_revoke.organizations_revoke import OrganizationsRevoke
from .register.register import Register

if TYPE_CHECKING:
    from ..hook0_api import Hook0API


class OrganizationsManagement:
    def __init__(self, parent: "Hook0API"):
        """


        Args:
            parent: The parent client to use for the requests
        """
        self.parent = parent

        self.organizations_list = OrganizationsList(parent=parent).organizations_list
        self.organizations_create = OrganizationsCreate(
            parent=parent
        ).organizations_create
        self.organizations_get = OrganizationsGet(parent=parent).organizations_get
        self.organizations_edit = OrganizationsEdit(parent=parent).organizations_edit
        self.organizations_delete = OrganizationsDelete(
            parent=parent
        ).organizations_delete
        self.organizations_edit_role = OrganizationsEditRole(
            parent=parent
        ).organizations_edit_role
        self.organizations_invite = OrganizationsInvite(
            parent=parent
        ).organizations_invite
        self.organizations_revoke = OrganizationsRevoke(
            parent=parent
        ).organizations_revoke
        self.register = Register(parent=parent).register
