# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, TYPE_CHECKING

if TYPE_CHECKING:
    from ...hook0_api import Hook0API


class ServicetokenGet:
    def __init__(self, parent: "Hook0API"):
        self.parent = parent

    def servicetoken_get(
        self,
        service_token_id: str,
        organization_id: str,
    ) -> Any:
        """
        Retrieves details of a specific service token if it belongs to the specified organization and is still active.

        Args:
            service_token_id:
            organization_id:

        Returns:
            Response data
        """
        path = f"/api/v1/service_token/{service_token_id}"
        params = {}
        headers = {}
        if organization_id is not None:
            params["organization_id"] = organization_id
        json_data = None

        response = self.parent._make_request(
            method="GET",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
