# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

from typing import TYPE_CHECKING

from .applicationsecrets_read.applicationsecrets_read import ApplicationsecretsRead
from .applicationsecrets_create.applicationsecrets_create import (
    ApplicationsecretsCreate,
)
from .applicationsecrets_update.applicationsecrets_update import (
    ApplicationsecretsUpdate,
)
from .applicationsecrets_delete.applicationsecrets_delete import (
    ApplicationsecretsDelete,
)
from .applications_list.applications_list import ApplicationsList
from .applications_create.applications_create import ApplicationsCreate
from .applications_get.applications_get import ApplicationsGet
from .applications_update.applications_update import ApplicationsUpdate
from .applications_delete.applications_delete import ApplicationsDelete

if TYPE_CHECKING:
    from ..hook0_api import Hook0API


class ApplicationsManagement:
    def __init__(self, parent: "Hook0API"):
        """


        Args:
            parent: The parent client to use for the requests
        """
        self.parent = parent

        self.applicationsecrets_read = ApplicationsecretsRead(
            parent=parent
        ).applicationsecrets_read
        self.applicationsecrets_create = ApplicationsecretsCreate(
            parent=parent
        ).applicationsecrets_create
        self.applicationsecrets_update = ApplicationsecretsUpdate(
            parent=parent
        ).applicationsecrets_update
        self.applicationsecrets_delete = ApplicationsecretsDelete(
            parent=parent
        ).applicationsecrets_delete
        self.applications_list = ApplicationsList(parent=parent).applications_list
        self.applications_create = ApplicationsCreate(parent=parent).applications_create
        self.applications_get = ApplicationsGet(parent=parent).applications_get
        self.applications_update = ApplicationsUpdate(parent=parent).applications_update
        self.applications_delete = ApplicationsDelete(parent=parent).applications_delete
