# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from ....models.subscriptionpost import SubscriptionPost

from typing import Any, Optional, TYPE_CHECKING

if TYPE_CHECKING:
    from ...hook0_api import Hook0API


class SubscriptionsUpdate:
    def __init__(self, parent: "Hook0API"):
        self.parent = parent

    def subscriptions_update(
        self,
        subscription_id: str,
        request_body: Optional[SubscriptionPost] = None,
    ) -> Any:
        """
        Modifies an existing subscription, including its event types, target configuration, or metadata. The subscription must belong to the specified application.

        Args:
            subscription_id:
            request_body: Request body

        Returns:
            Response data
        """
        path = f"/api/v1/subscriptions/{subscription_id}"
        params = {}
        headers = {}
        json_data = request_body.model_dump() if request_body else None

        response = self.parent._make_request(
            method="PUT",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
