# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, TYPE_CHECKING

if TYPE_CHECKING:
    from ...hook0_api import Hook0API


class OrganizationsCreate:
    def __init__(self, parent: "Hook0API"):
        self.parent = parent

    def organizations_create(
        self,
        name: str,
    ) -> Any:
        """
        Create a new organization. An organization contains applications, members and optionaly a plan. Note that you will need to regenerate an authentication token to be able to see/use the newly created organization.

        Args:
            name: No description provided

        Returns:
            Response data
        """
        path = "/api/v1/organizations/"
        params = None
        headers = None
        json_data = {
            "name": name if name is not None else None,
        }
        json_data = {k: v for k, v in json_data.items() if v is not None}

        response = self.parent._make_request(
            method="POST",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
