# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, TYPE_CHECKING

if TYPE_CHECKING:
    from ...hook0_api import Hook0API


class OrganizationsDelete:
    def __init__(self, parent: "Hook0API"):
        self.parent = parent

    def organizations_delete(
        self,
        organization_id: str,
    ) -> Any:
        """
        Remove an organization you have write access to. Organization must not contain any application otherwise this will fail.

        Args:
            organization_id:

        Returns:
            Response data
        """
        path = f"/api/v1/organizations/{organization_id}/"
        params = {}
        headers = {}
        json_data = None

        response = self.parent._make_request(
            method="DELETE",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
