# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, TYPE_CHECKING

if TYPE_CHECKING:
    from ...hook0_api import Hook0API


class SubscriptionsGet:
    def __init__(self, parent: "Hook0API"):
        self.parent = parent

    def subscriptions_get(
        self,
        subscription_id: str,
    ) -> Any:
        """
        Retrieves details of a specific subscription if it belongs to the specified application and has not been deleted.

        Args:
            subscription_id:

        Returns:
            Response data
        """
        path = f"/api/v1/subscriptions/{subscription_id}"
        params = {}
        headers = {}
        json_data = None

        response = self.parent._make_request(
            method="GET",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
