# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, Optional, TYPE_CHECKING

if TYPE_CHECKING:
    from ...hook0_api import Hook0API


class EventsIngest:
    def __init__(self, parent: "Hook0API"):
        self.parent = parent

    def events_ingest(
        self,
        application_id: str,
        event_id: str,
        event_type: str,
        labels: Any,
        occurred_at: str,
        payload: str,
        payload_content_type: str,
        metadata: Optional[Any] = None,
    ) -> Any:
        """
        Send an event to your Hook0 application. Matching subscriptions will be triggered, if any.

        Args:
            application_id: No description provided
            event_id: No description provided
            event_type: No description provided
            labels: No description provided
            occurred_at: No description provided
            payload: No description provided
            payload_content_type: No description provided
            metadata: No description provided

        Returns:
            Response data
        """
        path = "/api/v1/event/"
        params = None
        headers = None
        json_data = {
            "application_id": application_id if application_id is not None else None,
            "event_id": event_id if event_id is not None else None,
            "event_type": event_type if event_type is not None else None,
            "labels": labels if labels is not None else None,
            "metadata": metadata if metadata is not None else None,
            "occurred_at": occurred_at if occurred_at is not None else None,
            "payload": payload if payload is not None else None,
            "payload_content_type": payload_content_type
            if payload_content_type is not None
            else None,
        }
        json_data = {k: v for k, v in json_data.items() if v is not None}

        response = self.parent._make_request(
            method="POST",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
