# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

from typing import TYPE_CHECKING

from .events_ingest.events_ingest import EventsIngest
from .eventtypes_list.eventtypes_list import EventtypesList
from .eventtypes_create.eventtypes_create import EventtypesCreate
from .eventtypes_get.eventtypes_get import EventtypesGet
from .eventtypes_delete.eventtypes_delete import EventtypesDelete
from .events_list.events_list import EventsList
from .events_get.events_get import EventsGet
from .events_replay.events_replay import EventsReplay
from .payload_content_types_list.payload_content_types_list import (
    PayloadContentTypesList,
)

if TYPE_CHECKING:
    from ..hook0_api import Hook0API


class EventsManagement:
    def __init__(self, parent: "Hook0API"):
        """


        Args:
            parent: The parent client to use for the requests
        """
        self.parent = parent

        self.events_ingest = EventsIngest(parent=parent).events_ingest
        self.eventtypes_list = EventtypesList(parent=parent).eventtypes_list
        self.eventtypes_create = EventtypesCreate(parent=parent).eventtypes_create
        self.eventtypes_get = EventtypesGet(parent=parent).eventtypes_get
        self.eventtypes_delete = EventtypesDelete(parent=parent).eventtypes_delete
        self.events_list = EventsList(parent=parent).events_list
        self.events_get = EventsGet(parent=parent).events_get
        self.events_replay = EventsReplay(parent=parent).events_replay
        self.payload_content_types_list = PayloadContentTypesList(
            parent=parent
        ).payload_content_types_list
