# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, TYPE_CHECKING

if TYPE_CHECKING:
    from ...hook0_api import Hook0API


class OrganizationsInvite:
    def __init__(self, parent: "Hook0API"):
        self.parent = parent

    def organizations_invite(
        self,
        organization_id: str,
        email: str,
        role: str,
    ) -> Any:
        """
        Give permission to a user to access an organization you have write access to. The user must already have a Hook0 account otherwise this will fail.

        Args:
            organization_id:
            email: No description provided
            role: No description provided

        Returns:
            Response data
        """
        path = f"/api/v1/organizations/{organization_id}/invite"
        params = {}
        headers = {}
        json_data = {
            "email": email if email is not None else None,
            "role": role if role is not None else None,
        }
        json_data = {k: v for k, v in json_data.items() if v is not None}

        response = self.parent._make_request(
            method="POST",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
