# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

from typing import TYPE_CHECKING

from .requestattempts_read.requestattempts_read import RequestattemptsRead
from .response_get.response_get import ResponseGet
from .subscriptions_list.subscriptions_list import SubscriptionsList
from .subscriptions_create.subscriptions_create import SubscriptionsCreate
from .subscriptions_get.subscriptions_get import SubscriptionsGet
from .subscriptions_update.subscriptions_update import SubscriptionsUpdate
from .subscriptions_delete.subscriptions_delete import SubscriptionsDelete

if TYPE_CHECKING:
    from ..hook0_api import Hook0API


class SubscriptionsManagement:
    def __init__(self, parent: "Hook0API"):
        """


        Args:
            parent: The parent client to use for the requests
        """
        self.parent = parent

        self.requestattempts_read = RequestattemptsRead(
            parent=parent
        ).requestattempts_read
        self.response_get = ResponseGet(parent=parent).response_get
        self.subscriptions_list = SubscriptionsList(parent=parent).subscriptions_list
        self.subscriptions_create = SubscriptionsCreate(
            parent=parent
        ).subscriptions_create
        self.subscriptions_get = SubscriptionsGet(parent=parent).subscriptions_get
        self.subscriptions_update = SubscriptionsUpdate(
            parent=parent
        ).subscriptions_update
        self.subscriptions_delete = SubscriptionsDelete(
            parent=parent
        ).subscriptions_delete
