# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, TYPE_CHECKING

if TYPE_CHECKING:
    from ...hook0_api import Hook0API


class EventtypesDelete:
    def __init__(self, parent: "Hook0API"):
        self.parent = parent

    def eventtypes_delete(
        self,
        event_type_name: str,
        application_id: str,
    ) -> Any:
        """
        Marks an event type as deactivated, preventing it from being used for new event emissions. Existing events using this type remain unaffected.

        Args:
            event_type_name:
            application_id:

        Returns:
            Response data
        """
        path = f"/api/v1/event_types/{event_type_name}"
        params = {}
        headers = {}
        if application_id is not None:
            params["application_id"] = application_id
        json_data = None

        response = self.parent._make_request(
            method="DELETE",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
