# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, Optional, TYPE_CHECKING

if TYPE_CHECKING:
    from ...hook0_api import Hook0API


class InstanceHealth:
    def __init__(self, parent: "Hook0API"):
        self.parent = parent

    def instance_health(
        self,
        key: Optional[str] = None,
    ) -> Any:
        """
        Get an object that shows if this instance is up.

        Args:
            key:

        Returns:
            Response data
        """
        path = "/api/v1/health/"
        params = {}
        headers = {}
        if key is not None:
            params["key"] = key
        json_data = None

        response = self.parent._make_request(
            method="GET",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
