# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, Optional, TYPE_CHECKING

if TYPE_CHECKING:
    from ...hook0_api import Hook0API


class RequestattemptsRead:
    def __init__(self, parent: "Hook0API"):
        self.parent = parent

    def requestattempts_read(
        self,
        application_id: str,
        event_id: Optional[str] = None,
        subscription_id: Optional[str] = None,
    ) -> Any:
        """
        Retrieves the most recent attempts to deliver events to subscriptions for a given application. Request attempts track the status and history of event deliveries, including retries and failures.

        Args:
            application_id:
            event_id:
            subscription_id:

        Returns:
            Response data
        """
        path = "/api/v1/request_attempts/"
        params = {}
        headers = {}
        if application_id is not None:
            params["application_id"] = application_id
        if event_id is not None:
            params["event_id"] = event_id
        if subscription_id is not None:
            params["subscription_id"] = subscription_id
        json_data = None

        response = self.parent._make_request(
            method="GET",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
