# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, TYPE_CHECKING

if TYPE_CHECKING:
    from ...hook0_api import Hook0API


class EventtypesGet:
    def __init__(self, parent: "Hook0API"):
        self.parent = parent

    def eventtypes_get(
        self,
        event_type_name: str,
        application_id: str,
    ) -> Any:
        """
        Retrieves details of a specific event type if it exists within the given application. Event types define the structure of emitted events.

        Args:
            event_type_name:
            application_id:

        Returns:
            Response data
        """
        path = f"/api/v1/event_types/{event_type_name}"
        params = {}
        headers = {}
        if application_id is not None:
            params["application_id"] = application_id
        json_data = None

        response = self.parent._make_request(
            method="GET",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
