# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, TYPE_CHECKING

if TYPE_CHECKING:
    from ...hook0_api import Hook0API


class AuthLogout:
    def __init__(self, parent: "Hook0API"):
        self.parent = parent

    def auth_logout(
        self,
    ) -> Any:
        """
        Revoke all tokens associated to the current session.

        Returns:
            Response data
        """
        path = "/api/v1/auth/logout"
        params = None
        headers = None
        json_data = None

        response = self.parent._make_request(
            method="POST",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
