# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, TYPE_CHECKING

if TYPE_CHECKING:
    from ...hook0_api import Hook0API


class EventsReplay:
    def __init__(self, parent: "Hook0API"):
        self.parent = parent

    def events_replay(
        self,
        event_id: str,
        application_id: str,
    ) -> Any:
        """
        Trigger existing subscriptions matching an existing event, which will result in webhook being send again.

        Args:
            event_id:
            application_id: No description provided

        Returns:
            Response data
        """
        path = f"/api/v1/events/{event_id}/replay"
        params = {}
        headers = {}
        json_data = {
            "application_id": application_id if application_id is not None else None,
        }
        json_data = {k: v for k, v in json_data.items() if v is not None}

        response = self.parent._make_request(
            method="POST",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
