# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, TYPE_CHECKING

if TYPE_CHECKING:
    from ...hook0_api import Hook0API


class EventsList:
    def __init__(self, parent: "Hook0API"):
        self.parent = parent

    def events_list(
        self,
        application_id: str,
    ) -> Any:
        """
        Retrieves the last 100 ingested events for a given application.

        Args:
            application_id:

        Returns:
            Response data
        """
        path = "/api/v1/events/"
        params = {}
        headers = {}
        if application_id is not None:
            params["application_id"] = application_id
        json_data = None

        response = self.parent._make_request(
            method="GET",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
