# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, TYPE_CHECKING

if TYPE_CHECKING:
    from ...hook0_api import Hook0API


class OrganizationsRevoke:
    def __init__(self, parent: "Hook0API"):
        self.parent = parent

    def organizations_revoke(
        self,
        organization_id: str,
        user_id: str,
    ) -> Any:
        """
        Remove permission of a user to access an organization you have write access to.

        Args:
            organization_id:
            user_id: No description provided

        Returns:
            Response data
        """
        path = f"/api/v1/organizations/{organization_id}/invite"
        params = {}
        headers = {}
        json_data = {
            "user_id": user_id if user_id is not None else None,
        }
        json_data = {k: v for k, v in json_data.items() if v is not None}

        response = self.parent._make_request(
            method="DELETE",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
