# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, TYPE_CHECKING

if TYPE_CHECKING:
    from ...hook0_api import Hook0API


class ResponseGet:
    def __init__(self, parent: "Hook0API"):
        self.parent = parent

    def response_get(
        self,
        application_id: str,
        response_id: str,
    ) -> Any:
        """
        A response is produced when a request attempt is processed. Response IDs can be obtained from request attempts details.

        Args:
            application_id:
            response_id:

        Returns:
            Response data
        """
        path = f"/api/v1/responses/{response_id}"
        params = {}
        headers = {}
        if application_id is not None:
            params["application_id"] = application_id
        json_data = None

        response = self.parent._make_request(
            method="GET",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
