# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, Optional, TYPE_CHECKING

if TYPE_CHECKING:
    from ...hook0_api import Hook0API


class OrganizationsEdit:
    def __init__(self, parent: "Hook0API"):
        self.parent = parent

    def organizations_edit(
        self,
        organization_id: str,
        request_body: Optional[OrganizationPost] = None,
    ) -> Any:
        """
        Note that you will need to regenerate a JWT to be able to see the updated name of the organization.

        Args:
            organization_id:
            request_body: Request body

        Returns:
            Response data
        """
        path = f"/api/v1/organizations/{organization_id}/"
        params = {}
        headers = {}
        json_data = request_body.model_dump() if request_body else None

        response = self.parent._make_request(
            method="PUT",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
