# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, TYPE_CHECKING

if TYPE_CHECKING:
    from ...hook0_api import Hook0API


class ApplicationsList:
    def __init__(self, parent: "Hook0API"):
        self.parent = parent

    def applications_list(
        self,
        organization_id: str,
    ) -> Any:
        """
        Retrieves all applications.

        Args:
            organization_id:

        Returns:
            Response data
        """
        path = "/api/v1/applications/"
        params = {}
        headers = {}
        if organization_id is not None:
            params["organization_id"] = organization_id
        json_data = None

        response = self.parent._make_request(
            method="GET",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
