# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

from typing import TYPE_CHECKING

from .errors_list.errors_list import ErrorsList
from .instance_health.instance_health import InstanceHealth
from .instance_get.instance_get import InstanceGet
from .quotas_get.quotas_get import QuotasGet

if TYPE_CHECKING:
    from ..hook0_api import Hook0API


class Hook0:
    def __init__(self, parent: "Hook0API"):
        """


        Args:
            parent: The parent client to use for the requests
        """
        self.parent = parent

        self.errors_list = ErrorsList(parent=parent).errors_list
        self.instance_health = InstanceHealth(parent=parent).instance_health
        self.instance_get = InstanceGet(parent=parent).instance_get
        self.quotas_get = QuotasGet(parent=parent).quotas_get
