# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

# TODO: not implemented

from typing import Any, TYPE_CHECKING

if TYPE_CHECKING:
    from ...hook0_api import Hook0API


class EventtypesCreate:
    def __init__(self, parent: "Hook0API"):
        self.parent = parent

    def eventtypes_create(
        self,
        application_id: str,
        resource_type: str,
        service: str,
        verb: str,
    ) -> Any:
        """
        Defines a new event type for an application. Event types help categorize and structure emitted events, making them easier to manage and subscribe to.

        Args:
            application_id: No description provided
            resource_type: No description provided
            service: No description provided
            verb: No description provided

        Returns:
            Response data
        """
        path = "/api/v1/event_types/"
        params = None
        headers = None
        json_data = {
            "application_id": application_id if application_id is not None else None,
            "resource_type": resource_type if resource_type is not None else None,
            "service": service if service is not None else None,
            "verb": verb if verb is not None else None,
        }
        json_data = {k: v for k, v in json_data.items() if v is not None}

        response = self.parent._make_request(
            method="POST",
            path=path,
            params=params,
            headers=headers,
            json_data=json_data,
        )
        return response.json()
