# generated by borea

# if you want to edit this file, add it to ignores in borea.config.json, glob syntax

from typing import TYPE_CHECKING

from .auth_begin_reset_password.auth_begin_reset_password import AuthBeginResetPassword
from .auth_login.auth_login import AuthLogin
from .auth_logout.auth_logout import AuthLogout
from .auth_change_password.auth_change_password import AuthChangePassword
from .auth_refresh.auth_refresh import AuthRefresh
from .auth_reset_password.auth_reset_password import AuthResetPassword
from .auth_verify_email.auth_verify_email import AuthVerifyEmail

if TYPE_CHECKING:
    from ..hook0_api import Hook0API


class UserAuthentication:
    def __init__(self, parent: "Hook0API"):
        """


        Args:
            parent: The parent client to use for the requests
        """
        self.parent = parent

        self.auth_begin_reset_password = AuthBeginResetPassword(
            parent=parent
        ).auth_begin_reset_password
        self.auth_login = AuthLogin(parent=parent).auth_login
        self.auth_logout = AuthLogout(parent=parent).auth_logout
        self.auth_change_password = AuthChangePassword(
            parent=parent
        ).auth_change_password
        self.auth_refresh = AuthRefresh(parent=parent).auth_refresh
        self.auth_reset_password = AuthResetPassword(parent=parent).auth_reset_password
        self.auth_verify_email = AuthVerifyEmail(parent=parent).auth_verify_email
